### ISSUE TITLE
Invalid Authentication - HA 2024.4.1 ?

### ISSUE THREAD

**Issue by Roving-Ronin** [JacobsenKim/ha_huawei_solar_replicate#1]
Hi @JacobsenKim,

Just wondering if you might have had any luck running this with

![image](https://github.com/JacobsenKim/ha_huawei_solar_replicate/assets/108674933/4860f47f-fe9f-4ba9-8cb1-c9c44cc588d1)

______________________________

I have just setup a new 'TEST HA' to run your package upon, and tried linking to two different HA's (one remote and another on local network) and both report the same errors in their log files.

Both source HA's have a Long-Lived Access Token created,. and entered into the yaml as required (and URL / IP of source updated).

______________________________

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:138
integration: HTTP (documentation, issues)
First occurred: 13:34:16 (55 occurrences)
Last logged: 13:36:21

Login attempt or request with invalid authentication from 10.0.0.33 (10.0.0.33). Requested URL: '/api/states/sensor.inverter_daily_yield'. (HomeAssistant/2024.4.1 httpx/0.27.0 Python/3.12)
Login attempt or request with invalid authentication from 10.0.0.33 (10.0.0.33). Requested URL: '/api/states/sensor.inverter_active_power'. (HomeAssistant/2024.4.1 httpx/0.27.0 Python/3.12)
Login attempt or request with invalid authentication from 10.0.0.33 (10.0.0.33). Requested URL: '/api/states/sensor.battery_day_charge'. (HomeAssistant/2024.4.1 httpx/0.27.0 Python/3.12)
Login attempt or request with invalid authentication from 10.0.0.33 (10.0.0.33). Requested URL: '/api/states/sensor.inverter_input_power_2'. (HomeAssistant/2024.4.1 httpx/0.27.0 Python/3.12)
Login attempt or request with invalid authentication from 10.0.0.33 (10.0.0.33). Requested URL: '/api/states/sensor.battery_state_of_capacity'. (HomeAssistant/2024.4.1 httpx/0.27.0 Python/3.12)

**Comment by Roving-Ronin** [comment]
Please ignore, just updated to all the latest HA versions across all instances and it decided to just start working. \<facepalm> Thanks.

**Comment by JacobsenKim** [comment]
i have only try this local

here is my source HA atm.

![Skærmbillede 2024-04-09 021317](https://github.com/JacobsenKim/ha_huawei_solar_replicate/assets/157890151/2bf64466-636d-4c25-bf20-d2f127d67482)


and my target HA

![Skærmbillede 2024-04-09 021410](https://github.com/JacobsenKim/ha_huawei_solar_replicate/assets/157890151/57d86f3c-e363-4bda-8ef3-f973fa4b7c3b)

i just update target to 2024.4.2 and i dont get the problem, now also update to 2024.4.2 on source and i dont get the problem, might be something related to 2024.4.0 and some rest/token


Nice you got it working.
